// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: register.proto

package server

import (
	"context"
	register2 "grpc-common/ucenter/types/register"
	"ucenter/internal/logic"
	"ucenter/internal/svc"
)

type RegisterServer struct {
	svcCtx *svc.ServiceContext
	register2.UnimplementedRegisterServer
}

func NewRegisterServer(svcCtx *svc.ServiceContext) *RegisterServer {
	return &RegisterServer{
		svcCtx: svcCtx,
	}
}

func (s *RegisterServer) RegisterByPhone(ctx context.Context, in *register2.RegReq) (*register2.RegRes, error) {
	l := logic.NewRegisterByPhoneLogic(ctx, s.svcCtx)
	return l.RegisterByPhone(in)
}
